# Generated by Django 6.0.7 on 2026-08-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_profile_picture'),
        ('user', '0005_alter_role_id'),
    ]

    operations = [
    ]
